[terminal]
shell = "/usr/bin/zsh"

[general]
import = ["./themes/catppuccin-mocha.toml"]


[window]
decorations = "none"
opacity = 0.9
# startup_mode = "Fullscreen"

[font]
normal = { family = "MonaspiceNe Nerd Font", style = "Regular" }
bold = { family = "MonaspiceNe Nerd Font", style = "Bold" }
italic = { family = "MonaspiceNe Nerd Font", style = "Italic" }
bold_italic = { family = "MonaspiceNe Nerd Font", style = "Bold Italic" }

size = 13

[selection]
save_to_clipboard = true

[cursor]
style = { shape = "Block", blinking = "On" }
thickness = 0.2

[mouse]
hide_when_typing = true
